openapi: 3.0.3
info:
  title: Rokwire Polls Building Block API
  description: Polls Building Block API Documentation
  version: 1.0.21
servers:
  - url: 'https://api.rokwire.illinois.edu/polls'
    description: Production server
  - url: 'https://api-test.rokwire.illinois.edu/polls'
    description: Test server
  - url: 'https://api-dev.rokwire.illinois.edu/polls'
    description: Development server
  - url: 'http://localhost/polls'
    description: Local server
tags:
  - name: Client
    description: Client applications APIs.
paths: null
