openapi: 3.0.3
info:
  title: Rokwire Polls Building Block API
  description: Polls Building Block API Documentation
  version: 1.1.0
servers:
  - url: 'https://api.rokwire.illinois.edu/polls'
    description: Production server
  - url: 'https://api-test.rokwire.illinois.edu/polls'
    description: Test server
  - url: 'https://api-dev.rokwire.illinois.edu/polls'
    description: Development server
  - url: 'http://localhost/polls'
    description: Local server
tags:
  - name: Client
    description: Client applications APIs.
paths:
  #Client
  /api/polls:
    $ref: "./resources/client/polls.yaml"
  /api/polls/{id}:
    $ref: "./resources/client/pollsid.yaml"
  /api/polls/{id}/events:
    $ref: "./resources/client/pollsid-events.yaml"
  /api/polls/{id}/vote:
    $ref: "./resources/client/pollsid-vote.yaml"
  /api/polls/{id}/start:
    $ref: "./resources/client/pollsid-start.yaml"
  /api/polls/{id}/end:
    $ref: "./resources/client/pollsid-end.yaml"
  /api/surveys:
    $ref: "./resources/client/surveys.yaml"     
  /api/surveys/{id}:
    $ref: "./resources/client/surveysid.yaml"
  /api/survey-responses:
    $ref: "./resources/client/survey-responses.yaml"     
  /api/survey-responses/{id}:
    $ref: "./resources/client/survey-responsesid.yaml"     

  #Admin
  /api/admin/surveys:
    $ref: "./resources/admin/surveys.yaml"     
  /api/admin/surveys/{id}:
    $ref: "./resources/admin/surveysid.yaml"

components:
  securitySchemes:
      bearerAuth:            # arbitrary name for the security scheme
        type: http
        scheme: bearer
        bearerFormat: JWT
  schemas:
    $ref: "./schemas/index.yaml"